### ISSUE TITLE
Test against WordPress 5.8

### ISSUE THREAD

**Issue by jeffpaul** [10up/10up-sitemaps#10]
**Is your enhancement related to a problem? Please describe.**
 Once WordPress 5.8 is released, we'll want to test 10up Sitemaps to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test 10up Sitemaps on WordPress 5.8
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by BBerg10up** [comment]
@jeffpaul, this one is all set. Tested against 5.8.1 and had no issues locally with running `wp tenup-sitemaps generate` and generating sitemaps, ie:
![image](https://user-images.githubusercontent.com/72762903/139001311-0398f40f-2814-4abb-b967-6835ce112f9e.png)

**Comment by jeffpaul** [comment]
@BBerg10up do you want to take a stab at bumping the tested-up-to values in the plugin?

**Comment by BBerg10up** [comment]
Yup, just bumped it: 
https://github.com/10up/10up-sitemaps/commit/a5e96698534732aa46e4f46aa1f50836af092ba8
