### ISSUE TITLE
Test against WordPress 5.9

### ISSUE THREAD

**Issue by jeffpaul** [10up/10up-sitemaps#12]
**Is your enhancement related to a problem? Please describe.**
 Once WordPress 5.9 is released, we'll want to test 10up Sitemaps to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test 10up Sitemaps on WordPress 5.9
- [x] open issues for any incompatibilities noted in testing
- [x] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: https://github.com/10up/10up-sitemaps/issues/10

**Comment by jamesmorrison** [comment]
@jeffpaul I've tested 10up Sitemaps against WP 5.9.1; I found a bug with an undefined index - which I've raised an issue for here: https://github.com/10up/10up-sitemaps/issues/14 and fixed here: https://github.com/10up/10up-sitemaps/pull/13

I believe this can be closed, subject to any further testing required.

**Comment by jeffpaul** [comment]
@jamesmorrison in that case probably fine in #13 to bump the tested-up-to version in README.md then and mark this issue as being closed in #13 as well... thanks!

**Comment by jamesmorrison** [comment]
@jeffpaul The only mention of the WP version tested up to is in the README.md file (the "WordPress tested up to version" image); is there anywhere else I should add this?

**Comment by jeffpaul** [comment]
@jamesmorrison nope, there's no `readme.txt` for this plugin as its not distributed to WP.org, so the `README.md` location is the only / correct one, thanks!

**Comment by sudip-md** [comment]
@jeffpaul @ankitguptaindia Working as expected. Ready to release.
