### ISSUE TITLE
Add test Cases in Test Lodge - 10up Sitemaps

### ISSUE THREAD

**Issue by sudip-md** [10up/10up-sitemaps#15]
### Describe your question

Add test Cases in Test Lodge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankitguptaindia** [comment]
Hi @sudip-md when you have some moment, please move [Test Lodge's Test Cases](https://app.testlodge.com/a/23604/projects/45479/suites/201939) to Wiki pages here. Thank you! 

- **[Guide for Creating Critical Flow of 10up OSS Projects](https://docs.google.com/document/d/1rNv_jHxsQT-AKSJ9QC2HGH-rRKAlTJOoGBtP10w_zV0/edit#heading=h.ucn4farfwxyf).**

**Comment by sudip-md** [comment]
@ankitguptaindia I have added test Cases to wiki
https://github.com/10up/10up-sitemaps/wiki/Critical-Flows-for-10up-Sitemap
